### ISSUE TITLE
Planning meeting 14/11/22

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/medication-reviews#38]
- [ ] Redact & round table_1 (CW)
- [x]  Plot measures for all medication review codes (CW)
- [x] Format deciles to match other plots (CW) #40 
- [x] Create issues - for all meds codelist - CW https://github.com/opensafely/codelist-development/issues/247
- [x] Sign off all meds codelist - VS - CW to now publish, (VS unable to edit)
- [ ] High risk drugs codelist - teratogenics/addictives [high risk drugs codelists](https://github.com/opensafely/codelist-development/issues/246) VS
- [x] Add high dose opioids to addictive meds codelist - VS/CW discuss
- [x] Check for codelist rot - VS
- [ ] Update to final med review all types codelist - CW
- [ ] Add "on high risk drugs" to study breakdown - CW
- [x] Add 12m data for allmedrev - CW
- [ ] Age/sex standardisation - CW

- [x] Presentation for [Team Talks](https://docs.google.com/presentation/d/1rWWSNqGbcHiFWfKOTlILLYFUqi7bIpckHVuhXm7fk_Y/edit#slide=id.p1)

- [ ] Write [paper](https://docs.google.com/document/d/1_VgllblkhVw2AxUAPPWGPWy06c-4pwYWxrpZ3haXJwI/edit)

Future:
- [ ] Rerun MR joiner with updated ethnicity
- [ ] Y-axis setting - MR 800 per 1000. SMR 150 per 1000.
- [ ] Age/sex standardisation - https://github.com/opensafely/hospital-disruption-research/blob/master/analysis/rate_calculations.py#L99
- [ ]  Requests outputs - table_1 (CW)
- [ ] Get monthly and 12m data for MR / SMR rates

**Comment by chrisjwood16** [comment]
Moved outstanding actions to #41
