### ISSUE TITLE
Paper writing

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/medication-reviews#69]
- [x] Get SMR breakdowns for all categories inc high risk drugs #71
- [x] Age/sex standardise SMR measures #71 
- [x] Get ethnicity as 16 categories for table #70 
- [x] Rerun correct age bands/standardisation to get missing region and ethnicity (output standardised csvs for region and ethnicity) #68 
- [x] Plot SMR #76 
- [x] Relabel care home plot #76 
- [x] Fix agestandardisation for 90+ #77 
- [x] Check age/sex standardisation for IMD
- [x] Remove blue line from high risk drugs combine onto single plot?
- [x] Get updated codeuse count file
- [x] Request outputs #https://github.com/ebmdatalab/opensafely-output-review/issues/533
Once final paper doing ask for approval to run to latest date.

**Comment by chrisjwood16** [comment]
- [x] Disable redaction in standardisation function #81 
- [x] Add care_home_type to breakdown #81 
- [x] Remove missing from ethnicity & region plots (fix legend categories) #81 
- [x] White missing from non-stand ethnicity - same fix as above #81 
- [x] Convert care home types to binary pre-standardisation/redaction #82
- [x] Rerun correct_age_groups, standardisation, redact and round, redact and round standardised, plots and standardised plots

**Comment by chrisjwood16** [comment]
- [x] Explain in paper sequential redaction (e.g. LD, ethnicity redaction for SMRs good example)
- [x] Refactor legends for better fit
- [x] Update table 2
- [x] Update codeuse values
- [x] Update codelist for all med types
- [x] Add SMR results summary
